---
services:
  local-dev:
    container_name: local-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      # platforms:
      #   - linux/arm64
      #   - linux/amd64
      args:
        UBUNTU_VERSION: '24.04'
        PYTHON_VERSION: '3.13'
        USER_NAME: cli
        USER_UID: 1001
        USER_GID: 1001
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    image: ghcr.io/dceoy/local-dev:latest
    userns_mode: host
    network_mode: host
    volumes:
      - ${PWD}:/mnt/host
      - /var/run/docker.sock:/var/run/docker-host.sock
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnt/host
    environment:
      TZ: Asia/Tokyo
      LANG: en_US.UTF-8
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    command:
      - /usr/bin/zsh
      - -l
