---
services:
  local-dev:
    container_name: local-dev
    build:
      context: .
      dockerfile: Dockerfile
      # platforms:
      #   - linux/arm64
      #   - linux/amd64
    # platform: linux/arm64
    image: ghcr.io/dceoy/local-dev:latest
    volumes:
      - ${PWD}:/wd
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker-host.sock
    working_dir: /wd
    environment:
      TZ: Asia/Tokyo
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    command:
      - /usr/bin/zsh
      - -l
