---
services:
  local-dev:
    container_name: local-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      args:
        USER: dev
        UID: '1001'
        GID: '1001'
    image: ghcr.io/dceoy/local-dev:latest
    userns_mode: host
    user: 1001:1001
    network_mode: host
    volumes:
      - ${PWD}:/mnt/host
      - ${HOME}/.aws:/home/dev/.aws:ro
      - ${HOME}/.ssh:/home/dev/.ssh:ro
      - /var/run/docker.sock:/var/run/docker-host.sock
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnt/host
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    command:
      - /usr/bin/zsh
      - -l
