---
version: '3'

services:
  local-dev:
    container_name: local-dev
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ghcr.io/dceoy/local-dev:latest
    # platform: linux/arm64
    volumes:
      - ${PWD}:/wd
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
    working_dir: /wd
    environment:
      TZ: Asia/Tokyo
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    command:
      - /usr/bin/zsh
      - -l
