---
name: CI to GitHub Container Registry
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker-build-and-push:
    uses: dceoy/gh-actions-for-devops/.github/workflows/docker-build-and-push.yml@main
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
      platforms: linux/amd64,linux/arm64
      context: .
      file: ./Dockerfile
      push: true
    secrets:
      DOCKER_USER: ${{ github.actor }}
      DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
